# Gemfile for GitHub Pages (Actions uses this; avoid gems not in github-pages)
# Using remote_theme in _config.yml so we don't need the just-the-docs gem.
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# Windows may need:
# gem "wdm", "~> 0.1" if Gem.win_platform?
